"""Add industries table and industry_id to businesses

Revision ID: 812d272aab4f
Revises: d0e2a48e067c
Create Date: 2025-08-09 14:34:26.379383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812d272aab4f'
down_revision = 'd0e2a48e067c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=True)
    op.add_column('businesses', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'industries', ['industry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'industry_id')
    op.drop_index(op.f('ix_industries_slug'), table_name='industries')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###