"""Add cascade delete constraints to content table

Revision ID: d0e2a48e067c
Revises: 38cf5d198c3b
Create Date: 2025-08-09 11:31:21.076565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e2a48e067c'
down_revision = '38cf5d198c3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_campaign_id_fkey', 'content', type_='foreignkey')
    op.drop_constraint('content_business_id_fkey', 'content', type_='foreignkey')
    op.create_foreign_key(None, 'content', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'content', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.create_foreign_key('content_business_id_fkey', 'content', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('content_campaign_id_fkey', 'content', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###